const translations = {
    ar: {
        nav_home: 'الرئيسية',
        nav_depts: 'الأقسام',
        nav_doctors: 'الأطباء',
        nav_book: 'حجز موعد',
        lang_btn: 'English',
        dark_mode: 'الوضع الليلي',
hero_title1: 'رعاية صحية',
        hero_title2: 'تسبق المستقبل',
        hero_desc: 'مستشفى الحياة الحكومي في الكويت، أحدث التقنيات مع لمسة إنسانية. نخدم أكثر من مليون مريض سنويًا.',
        hero_btn1: 'احجز موعدك',
        hero_btn2: 'استكشف الأقسام',
        why_title: 'لماذا تختارنا',
        why_sub: 'مزايا تجعلنا الخيار الأول لصحتك',
        why1_title: 'تقنيات حديثة',
        why1_desc: 'أحدث الأجهزة الطبية',
        why2_title: 'أطباء خبراء',
        why2_desc: 'استشاريون معتمدون دولياً',
        why3_title: 'رعاية 24/7',
        why3_desc: 'طوارئ مفتوحة على مدار الساعة',
        why4_title: 'راحة المريض',
        why4_desc: 'غرف فندقية وإقامة مميزة',
        depts_title: 'أقسامنا المتطورة',
        depts_sub: 'نقدم رعاية شاملة عبر مراكز تميز عالمية',
        depts_link: 'عرض كل الأقسام',
        dept1_title: 'أمراض القلب',
        dept1_desc: 'أحدث قسطرة وعمليات قلب مفتوح',
        dept1_detail: 'يضم القسم 12 استشارياً، ويقدم خدمات القسطرة القلبية وجراحة القلب المفتوح على مدار الساعة. الموقع: المبنى الرئيسي، الطابق الثالث.',
        dept2_title: 'جراحة المخ والأعصاب',
        dept2_desc: 'تقنيات الملاحة العصبية',
        dept2_detail: 'نخبة من جراحي المخ والأعصاب يستخدمون أحدث تقنيات الملاحة العصبية. 8 استشاريين، تحويلة 502.',
        dept3_title: 'جراحة العظام',
        dept3_desc: 'تبديل مفاصل بالروبوت',
        dept3_detail: 'قسم متكامل لجراحة العظام والمفاصل، مع 15 استشارياً وروبوتات حديثة لتبديل المفاصل. تحويلة 210.',
        dept4_title: 'طب الأطفال',
        dept4_desc: 'رعاية فائقة للأطفال الخدج',
        dept4_detail: 'وحدة عناية مركزة لحديثي الولادة مجهزة بأحدث الأجهزة. 20 استشارياً و25 حضّانة. تحويلة 101.',
docs_title: 'نخبة من أطبائنا',
        docs_sub: 'فريق طبي مؤهل بأعلى الشهادات والخبرات',
        docs_link: 'عرض كل الأطباء',
        doc1_name: 'د. أحمد العمري',
        doc1_detail: 'استشاري أمراض القلب والقسطرة. الزمالة الأمريكية من هارفارد، 20 عامًا خبرة. العيادة: أحد، ثلاثاء، خميس 9-12.',
        doc2_name: 'د. سارة القحطاني',
        doc2_detail: 'استشارية جراحة المخ والأعصاب. الزمالة البريطانية، أستاذ مساعد في جامعة الكويت. العيادة: سبت، اثنين، أربعاء 10-2.',
        doc3_name: 'د. خالد الشمري',
        doc3_detail: 'استشاري جراحة العظام والمفاصل. الزمالة الألمانية، خبير الروبوتات الجراحية. العيادة: أحد، ثلاثاء، خميس 8-1.',
        doc4_name: 'د. منى الحربي',
        doc4_detail: 'استشارية طب الأطفال والحديثي الولادة. الزمالة الكندية، حاصلة على جائزة التميز الطبي. العيادة: سبت، اثنين، أربعاء 9-4.',
        book_title: 'احجز موعدك بذكاء',
        book_sub: 'املأ البيانات وسيتم تأكيد الحجز عبر البريد فوراً',
        form_name: 'الاسم الكامل',
        form_phone: 'رقم الجوال',
        form_email: 'البريد الإلكتروني',
        form_dept: 'القسم',
        form_date: 'التاريخ المفضل',
        form_time: 'الوقت المفضل',
        form_notes: 'ملاحظات إضافية',
        form_submit: 'تأكيد الحجز',
        footer_about: 'نموذج رعاية صحية حكومي متطور. نلتزم بأعلى معايير الجودة والسلامة.',
        quick_links: 'روابط سريعة',
        contact_us: 'تواصل معنا',
        phone: '2222 1234',
        email: 'info@alhayat.kw',
        address: 'الكويت، حولي، شارع بيروت',
        copyright: '© 2026 مستشفى الحياة الحكومي. قالب من <strong>موقعك</strong> – Mawqeak',
        depts_banner_title: 'أقسامنا الطبية المتطورة',
        depts_banner_desc: 'نقدم رعاية صحية شاملة عبر مراكز تميز عالمية مجهزة بأحدث التقنيات الطبية',
        dept1_full_desc: 'يقدم قسم أمراض القلب لدينا خدمات تشخيصية وعلاجية متكاملة باستخدام أحدث تقنيات القسطرة القلبية وجراحة القلب المفتوح. يضم القسم نخبة من الاستشاريين الحاصلين على زمالات دولية من أرقى الجامعات العالمية. نقدم أيضاً برامج متخصصة لإعادة التأهيل القلبي والإشراف الطبي المستمر.',
        dept1_hours: 'الأحد - الخميس: 7 صباحاً - 10 مساءً',
        dept1_location: 'المبنى الرئيسي - الطابق الثالث',
        dept1_ext: 'تحويلة: 301',
        dept1_consultants: '12 استشارياً',
        dept1_beds: '45 سريراً للعناية المركزة',
        dept1_extra: 'مواعيد فورية للحالات الطارئة',
        dept2_full_desc: 'نوفر رعاية متقدمة لأمراض الجهاز العصبي المركزي والطرفي، بما في ذلك جراحة الأورام الدماغية، وجراحة العمود الفقري، وجراحة الأعصاب الطرفية. نستخدم تقنيات الملاحة العصبية والمراقبة العصبية أثناء العمليات لضمان أعلى مستويات الدقة والأمان. قسمنا مزود بغرف عمليات ذكية.',
        dept2_hours: 'السبت - الخميس: 8 صباحاً - 8 مساءً',
        dept2_location: 'المبنى الغربي - الطابق الخامس',
        dept2_ext: 'تحويلة: 502',
        dept2_consultants: '8 استشاريين',
        dept2_beds: '30 سريراً للعناية العصبية',
        dept2_extra: 'العمليات المجدولة: أحد وأربعاء',
        dept3_full_desc: 'نقدم خدمات متكاملة في جراحة العظام والمفاصل، بدءاً من علاج الكسور والإصابات الرياضية وصولاً إلى عمليات تبديل المفاصل الروبوتية. نستخدم تقنيات الطباعة ثلاثية الأبعاد لتخطيط العمليات المعقدة، ونوفر برامج تأهيل طبيعي مكثفة داخل القسم لضمان سرعة التعافي.',
        dept3_hours: 'الأحد - الخميس: 8 صباحاً - 9 مساءً',
        dept3_location: 'مبنى الجراحات - الطابق الثاني',
        dept3_ext: 'تحويلة: 210',
        dept3_consultants: '15 استشارياً',
        dept3_beds: '55 سريراً للتنويم',
        dept3_extra: 'علاج طبيعي وتأهيل متكامل',
        dept4_full_desc: 'يوفر قسم الأطفال رعاية طبية شاملة للأطفال منذ الولادة وحتى سن المراهقة. نضم وحدة عناية مركزة لحديثي الولادة (NICU) مجهزة بأحدث الحاضنات وأجهزة التنفس الصناعي. فريقنا الطبي متخصص في أمراض القلب الخلقية، وأمراض الدم، والغدد الصماء لدى الأطفال.',
        dept4_hours: '24 ساعة / 7 أيام في الأسبوع',
        dept4_location: 'المبنى الرئيسي - الطابق الأرضي',
        dept4_ext: 'تحويلة: 101',
        dept4_consultants: '20 استشارياً',
        dept4_beds: '60 سريراً + 25 حضانة',
        dept4_extra: 'عيادات تخصصية يومياً',
        dept5_title: 'الطوارئ والإسعاف',
        dept5_full_desc: 'قسم الطوارئ لدينا مفتوح على مدار الساعة طوال أيام الأسبوع لاستقبال جميع الحالات الطارئة والحرجة. نضم فريقاً متكاملاً من أطباء الطوارئ والممرضين المتخصصين، مع غرف عمليات طوارئ مجهزة بالكامل. زمن الاستجابة للحالات الحرجة أقل من 5 دقائق.',
        dept5_hours: '24 ساعة / 7 أيام',
        dept5_location: 'المدخل الرئيسي - يسار البوابة',
        dept5_ext: 'تحويلة: 999',
        dept5_consultants: '25 طبيب طوارئ',
        dept5_beds: '40 سريراً للعناية الحرجة',
        dept5_extra: 'لا حاجة لموعد مسبق',
        dept6_title: 'طب وجراحة العيون',
        dept6_full_desc: 'نقدم خدمات شاملة للعيون تشمل فحوصات النظر الدقيقة، جراحات الساد (المياه البيضاء) بتقنية الفاكو، تصحيح الإبصار بالليزر، وعلاج أمراض الشبكية والجلوكوما. نستخدم أحدث أجهزة التصوير المقطعي للعين (OCT) لضمان تشخيص دقيق.',
        dept6_hours: 'السبت - الخميس: 9 صباحاً - 7 مساءً',
        dept6_location: 'المبنى الشرقي - الطابق الرابع',
        dept6_ext: 'تحويلة: 410',
        dept6_consultants: '10 استشاريين',
        dept6_beds: '20 سريراً',
        dept6_extra: 'عمليات الليزك كل يوم ثلاثاء',
        doctors_banner_title: 'نخبة من أطبائنا',
        doctors_banner_desc: 'فريق طبي متميز مؤهل بأعلى الشهادات والخبرات من أرقى الجامعات العالمية',
        doc1_specialty: 'استشاري أمراض القلب والقسطرة',
        doc1_full_desc: 'حاصل على الزمالة الأمريكية في أمراض القلب من جامعة هارفارد. لديه خبرة تزيد عن 20 عاماً في مجال القسطرة القلبية وجراحة القلب المفتوح. أجرى أكثر من 5000 عملية قسطرة ناجحة. عضو في الجمعية الأمريكية للقلب والكلية الأمريكية لأمراض القلب.',
        doc1_edu: 'دكتوراه الطب - جامعة الكويت',
        doc1_board: 'البورد الأمريكي - هارفارد',
        doc1_clinic: 'العيادة: أحد، ثلاثاء، خميس 9-12',
        doc1_ext: 'تحويلة: 301',
        doc2_specialty: 'استشارية جراحة المخ والأعصاب',
        doc2_full_desc: 'حاصلة على الزمالة البريطانية في جراحة المخ والأعصاب من جامعة كامبريدج. متخصصة في جراحة أورام المخ وجراحة العمود الفقري بالمنظار. لديها أكثر من 15 عاماً من الخبرة، وتعمل كأستاذ مساعد في كلية الطب بجامعة الكويت.',
        doc2_edu: 'دكتوراه الطب - جامعة الكويت',
        doc2_board: 'الزمالة البريطانية - كامبريدج',
        doc2_clinic: 'العيادة: سبت، اثنين، أربعاء 10-2',
        doc2_ext: 'تحويلة: 502',
        doc3_specialty: 'استشاري جراحة العظام والمفاصل',
        doc3_full_desc: 'حاصل على الزمالة الألمانية في جراحة العظام من جامعة هايدلبرغ. خبير في تقنيات تبديل المفاصل الروبوتية والجراحة بالمنظار. أجرى أكثر من 3000 عملية تبديل مفصل ناجحة. محاضر دولي في مجال الروبوتات الجراحية.',
        doc3_edu: 'دكتوراه الطب - جامعة الكويت',
        doc3_board: 'البورد الألماني - هايدلبرغ',
        doc3_clinic: 'العيادة: أحد، ثلاثاء، خميس 8-1',
        doc3_ext: 'تحويلة: 210',
        doc4_specialty: 'استشارية طب الأطفال والحديثي الولادة',
        doc4_full_desc: 'حاصلة على الزمالة الكندية في طب الأطفال من جامعة تورنتو. متخصصة في أمراض القلب الخلقية للأطفال ورعاية الخدج. لديها خبرة 18 عاماً في وحدات العناية المركزة لحديثي الولادة. حاصلة على جائزة التميز الطبي لعام 2023.',
        doc4_edu: 'بكالوريوس الطب - جامعة الكويت',
        doc4_board: 'الزمالة الكندية - تورنتو',
        doc4_clinic: 'العيادة: سبت، اثنين، أربعاء 9-4',
        doc4_ext: 'تحويلة: 101',
        doc5_specialty: 'استشاري طب وجراحة العيون',
        doc5_full_desc: 'حاصل على الزمالة الفرنسية في طب العيون من جامعة السوربون. متخصص في جراحات الساد وتصحيح الإبصار بالليزر. أجرى أكثر من 7000 عملية ليزك ناجحة. عضو في الجمعية الأوروبية لجراحة العيون والجمعية الأمريكية لطب العيون.',
        doc5_edu: 'دكتوراه الطب - جامعة الكويت',
        doc5_board: 'الزمالة الفرنسية - السوربون',
        doc5_clinic: 'العيادة: أحد، ثلاثاء، خميس 10-3',
        doc5_ext: 'تحويلة: 410',
        doc6_name: 'د. نورة المطيري',
        doc6_specialty: 'استشارية طب الطوارئ والإصابات',
        doc6_full_desc: 'حاصلة على الزمالة الأسترالية في طب الطوارئ من جامعة سيدني. متخصصة في إدارة الحالات الحرجة والإصابات المتعددة. لديها خبرة 12 عاماً في أقسام الطوارئ والكوارث. مدربة معتمدة في دعم الحياة المتقدم (ATLS).',
        doc6_edu: 'دكتوراه الطب - جامعة الكويت',
        doc6_board: 'الزمالة الأسترالية - سيدني',
        doc6_clinic: 'متواجدة في قسم الطوارئ 24/7',
        doc6_ext: 'تحويلة: 999',
        doc_book_btn: 'احجز موعداً مع الدكتور',
        modal_close: 'إغلاق',
        payment_title: 'طريقة الدفع',
payment_cod: 'دفع عند الاستلام',
payment_bank: 'تحويل بنكي',
bank_details_title: 'معلومات الحساب البنكي',
bank_name: 'بنك الكويت الوطني',
bank_account: 'رقم الحساب: 1234567890',
bank_iban: 'IBAN: KW12345678901234567890',
bank_swift: 'سويفت: NBOKKWKW',
upload_label: 'ارفع صورة إيصال التحويل',
upload_placeholder: 'اضغط أو اسحب الصورة هنا',
whatsapp_text: 'تواصل عبر الواتساب',
payment_modal_title: 'اختر طريقة الدفع',
confirm_booking: 'تأكيد وإرسال الحجز'
    },
    en: {
        nav_home: 'Home',
        nav_depts: 'Departments',
        nav_doctors: 'Doctors',
        nav_book: 'Appointment',
        lang_btn: 'العربية',
        dark_mode: 'Dark Mode',
        hero_title1: 'Healthcare',
        hero_title2: 'Ahead of the Future',
        hero_desc: 'Al-Hayat Government Hospital in Kuwait, cutting-edge technology with a human touch. Serving over a million patients annually.',
        hero_btn1: 'Book an Appointment',
        hero_btn2: 'Explore Departments',
        why_title: 'Why Choose Us',
        why_sub: 'Features that make us your first choice for health',
        why1_title: 'Modern Technology',
        why1_desc: 'Latest medical equipment',
        why2_title: 'Expert Doctors',
        why2_desc: 'Internationally certified consultants',
        why3_title: '24/7 Care',
        why3_desc: 'Emergency open around the clock',
        why4_title: 'Patient Comfort',
        why4_desc: 'Hotel-like rooms & premium stay',
        depts_title: 'Our Advanced Departments',
        depts_sub: 'Comprehensive care through world-class centers',
        depts_link: 'View All Departments',
        dept1_title: 'Cardiology',
        dept1_desc: 'Latest catheterization & open-heart surgeries',
        dept1_detail: '12 consultants, catheterization and open-heart surgeries 24/7. Located in the main building, third floor.',
        dept2_title: 'Neurosurgery',
        dept2_desc: 'Neuronavigation technologies',
        dept2_detail: 'Elite neurosurgeons using the latest neuronavigation. 8 consultants, ext. 502.',
        dept3_title: 'Orthopedics',
        dept3_desc: 'Robotic joint replacement',
        dept3_detail: 'Full orthopedic department with 15 consultants and modern robotic joint replacement. Ext. 210.',
        dept4_title: 'Pediatrics',
        dept4_desc: 'Advanced NICU care',
        dept4_detail: 'NICU with state-of-the-art equipment. 20 consultants, 25 incubators. Ext. 101.',
        docs_title: 'Our Distinguished Doctors',
        docs_sub: 'Highly qualified medical team with international expertise',
        docs_link: 'View All Doctors',
        doc1_name: 'Dr. Ahmed Al-Omari',
        doc1_detail: 'Cardiology Consultant. American board from Harvard, 20 years experience. Clinic: Sun, Tue, Thu 9-12.',
        doc2_name: 'Dr. Sarah Al-Qahtani',
        doc2_detail: 'Neurosurgery Consultant. British fellowship, Assistant Professor at Kuwait University. Clinic: Sat, Mon, Wed 10-2.',
        doc3_name: 'Dr. Khaled Al-Shammari',
        doc3_detail: 'Orthopedic Surgery Consultant. German board, robotic surgery expert. Clinic: Sun, Tue, Thu 8-1.',
        doc4_name: 'Dr. Mona Al-Harbi',
        doc4_detail: 'Pediatrics & Neonatology Consultant. Canadian fellowship, Medical Excellence Award. Clinic: Sat, Mon, Wed 9-4.',
        book_title: 'Smart Booking',
        book_sub: 'Fill in your details and receive instant email confirmation',
        form_name: 'Full Name',
        form_phone: 'Phone Number',
        form_email: 'Email Address',
        form_dept: 'Department',
        form_date: 'Preferred Date',
        form_time: 'Preferred Time',
        form_notes: 'Additional Notes',
        form_submit: 'Confirm Booking',
        footer_about: 'A model of advanced government healthcare. We adhere to the highest standards of quality and safety.',
        quick_links: 'Quick Links',
        contact_us: 'Contact Us',
        phone: '2222 1234',
        email: 'info@alhayat.kw',
        address: 'Kuwait, Hawally, Beirut Street',
        copyright: '© 2026 Al-Hayat Government Hospital. Template by <strong>Mawqeak</strong>',
        depts_banner_title: 'Our Advanced Medical Departments',
        depts_banner_desc: 'Comprehensive healthcare through world-class centers of excellence equipped with the latest medical technology',
        dept1_full_desc: 'Our Cardiology Department offers integrated diagnostic and therapeutic services using the latest cardiac catheterization and open-heart surgery techniques. The department includes elite consultants with international fellowships from top universities worldwide. We also provide specialized cardiac rehabilitation programs.',
        dept1_hours: 'Sun - Thu: 7 AM - 10 PM',
        dept1_location: 'Main Building - 3rd Floor',
        dept1_ext: 'Ext: 301',
        dept1_consultants: '12 Consultants',
        dept1_beds: '45 ICU Beds',
        dept1_extra: 'Immediate appointments for emergencies',
        dept2_full_desc: 'We provide advanced care for central and peripheral nervous system diseases, including brain tumor surgery, spinal surgery, and peripheral nerve surgery. We use neuronavigation and intraoperative neuromonitoring to ensure the highest levels of precision and safety. Our department is equipped with smart operating rooms.',
        dept2_hours: 'Sat - Thu: 8 AM - 8 PM',
        dept2_location: 'West Building - 5th Floor',
        dept2_ext: 'Ext: 502',
        dept2_consultants: '8 Consultants',
        dept2_beds: '30 Neuro ICU Beds',
        dept2_extra: 'Scheduled surgeries: Sun & Wed',
        dept3_full_desc: 'We offer integrated orthopedic and joint services, from fracture treatment and sports injuries to robotic joint replacement surgeries. We use 3D printing technologies to plan complex operations and provide intensive physiotherapy programs within the department to ensure rapid recovery.',
        dept3_hours: 'Sun - Thu: 8 AM - 9 PM',
        dept3_location: 'Surgery Building - 2nd Floor',
        dept3_ext: 'Ext: 210',
        dept3_consultants: '15 Consultants',
        dept3_beds: '55 Inpatient Beds',
        dept3_extra: 'Integrated physiotherapy & rehabilitation',
        dept4_full_desc: 'The Pediatric Department provides comprehensive medical care for children from birth through adolescence. We house a Neonatal Intensive Care Unit (NICU) equipped with the latest incubators and ventilators. Our medical team specializes in congenital heart diseases, hematology, and pediatric endocrinology.',
        dept4_hours: '24 Hours / 7 Days a Week',
        dept4_location: 'Main Building - Ground Floor',
        dept4_ext: 'Ext: 101',
        dept4_consultants: '20 Consultants',
        dept4_beds: '60 Beds + 25 Incubators',
        dept4_extra: 'Specialized clinics daily',
        dept5_title: 'Emergency & Ambulance',
        dept5_full_desc: 'Our Emergency Department is open 24/7 to receive all urgent and critical cases. We have a full team of specialized emergency physicians and nurses, with fully equipped emergency operating rooms. Critical case response time is under 5 minutes.',
        dept5_hours: '24 Hours / 7 Days',
        dept5_location: 'Main Entrance - Left Side',
        dept5_ext: 'Ext: 999',
        dept5_consultants: '25 Emergency Physicians',
        dept5_beds: '40 Critical Care Beds',
        dept5_extra: 'No prior appointment needed',
        dept6_title: 'Ophthalmology',
        dept6_full_desc: 'We offer comprehensive eye services including precise vision examinations, phaco cataract surgery, laser vision correction, and treatment of retinal diseases and glaucoma. We use the latest Optical Coherence Tomography (OCT) for accurate diagnosis.',
        dept6_hours: 'Sat - Thu: 9 AM - 7 PM',
        dept6_location: 'East Building - 4th Floor',
        dept6_ext: 'Ext: 410',
        dept6_consultants: '10 Consultants',
        dept6_beds: '20 Beds',
        dept6_extra: 'LASIK surgeries every Tuesday',
        doctors_banner_title: 'Our Distinguished Doctors',
        doctors_banner_desc: 'An outstanding medical team with the highest international degrees and experience from top universities worldwide',
        doc1_specialty: 'Cardiology & Catheterization Consultant',
        doc1_full_desc: 'American board-certified in Cardiology from Harvard University. Over 20 years of experience in cardiac catheterization and open-heart surgery. Performed more than 5000 successful catheterizations. Member of the American Heart Association and American College of Cardiology.',
        doc1_edu: 'MD - Kuwait University',
        doc1_board: 'American Board - Harvard',
        doc1_clinic: 'Clinic: Sun, Tue, Thu 9 AM - 12 PM',
        doc1_ext: 'Ext: 301',
        doc2_specialty: 'Neurosurgery Consultant',
        doc2_full_desc: 'British fellowship in Neurosurgery from Cambridge University. Specialized in brain tumor surgery and endoscopic spinal surgery. Over 15 years of experience, and serves as Assistant Professor at Kuwait University Faculty of Medicine.',
        doc2_edu: 'MD - Kuwait University',
        doc2_board: 'British Fellowship - Cambridge',
        doc2_clinic: 'Clinic: Sat, Mon, Wed 10 AM - 2 PM',
        doc2_ext: 'Ext: 502',
        doc3_specialty: 'Orthopedic Surgery Consultant',
        doc3_full_desc: 'German board-certified in Orthopedics from Heidelberg University. Expert in robotic joint replacement and arthroscopic surgery. Performed over 3000 successful joint replacements. International lecturer in surgical robotics.',
        doc3_edu: 'MD - Kuwait University',
        doc3_board: 'German Board - Heidelberg',
        doc3_clinic: 'Clinic: Sun, Tue, Thu 8 AM - 1 PM',
        doc3_ext: 'Ext: 210',
        doc4_specialty: 'Pediatrics & Neonatology Consultant',
        doc4_full_desc: 'Canadian fellowship in Pediatrics from the University of Toronto. Specialized in congenital heart diseases in children and premature infant care. 18 years of experience in NICUs. Recipient of the 2023 Medical Excellence Award.',
        doc4_edu: 'MBBS - Kuwait University',
        doc4_board: 'Canadian Fellowship - Toronto',
        doc4_clinic: 'Clinic: Sat, Mon, Wed 9 AM - 4 PM',
        doc4_ext: 'Ext: 101',
        doc5_specialty: 'Ophthalmology Consultant',
        doc5_full_desc: 'French fellowship in Ophthalmology from Sorbonne University. Specialized in cataract surgery and laser vision correction. Performed over 7000 successful LASIK surgeries. Member of the European Society of Ophthalmology and American Academy of Ophthalmology.',
        doc5_edu: 'MD - Kuwait University',
        doc5_board: 'French Fellowship - Sorbonne',
        doc5_clinic: 'Clinic: Sun, Tue, Thu 10 AM - 3 PM',
        doc5_ext: 'Ext: 410',
        doc6_name: 'Dr. Noura Al-Mutairi',
        doc6_specialty: 'Emergency Medicine & Trauma Consultant',
        doc6_full_desc: 'Australian fellowship in Emergency Medicine from the University of Sydney. Specialized in critical case management and multiple trauma. 12 years of experience in emergency and disaster departments. Certified Advanced Trauma Life Support (ATLS) instructor.',
        doc6_edu: 'MD - Kuwait University',
        doc6_board: 'Australian Fellowship - Sydney',
        doc6_clinic: 'Available in ER 24/7',
        doc6_ext: 'Ext: 999',
        doc_book_btn: 'Book an Appointment',
        modal_close: 'Close',
        payment_title: 'Payment Method',
payment_cod: 'Cash on Delivery',
payment_bank: 'Bank Transfer',
bank_details_title: 'Bank Account Information',
bank_name: 'National Bank of Kuwait',
bank_account: 'Account Number: 1234567890',
bank_iban: 'IBAN: KW12345678901234567890',
bank_swift: 'SWIFT: NBOKKWKW',
upload_label: 'Upload Payment Receipt',
upload_placeholder: 'Click or drag image here',
whatsapp_text: 'Contact via WhatsApp',
payment_modal_title: 'Select Payment Method',
confirm_booking: 'Confirm and Send Booking'
    }
};

let currentLang = 'ar';

function setLanguage(lang) {
    currentLang = lang;
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });
    const langToggle = document.getElementById('langToggle');
    if (langToggle) {
        langToggle.innerHTML = lang === 'ar' ? '<i class="fas fa-globe"></i> English' : '<i class="fas fa-globe"></i> العربية';
    }
    localStorage.setItem('lang', lang);
    window.dispatchEvent(new Event('languageChanged'));
}

function switchLanguage() {
    const newLang = currentLang === 'ar' ? 'en' : 'ar';
    setLanguage(newLang);
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('lang') || 'ar';
    setLanguage(savedLang);
    const langToggle = document.getElementById('langToggle');
    if (langToggle) {
        langToggle.addEventListener('click', switchLanguage);
    }
});
